name: backdrop-test
recipe: backdrop
config:
  webroot: backdrop
  php: '7.0'
  via: nginx
  database: mariadb:10.1
  backdrush: '1.0.0'
  xdebug: false
  services:
    mailhog:
      type: mailhog
      hogfrom:
        - appserver
    node-cli:
      type: node:11
      globals:
        gulp-cli: "latest"
  tooling:
    npm:
      service: node-cli
    node:
      service: node-cli
    gulp:
      service: node-cli
